#!/usr/bin/env bats
# tests/container/test_entrypoint_brave_key.bats
# Run: bats tests/container/test_entrypoint_brave_key.bats
#
# Regression gate for #908 — a BRAVE_API_KEY containing shell/sed/supervisord
# metacharacters must not brick boot. Two consuming surfaces, two mechanisms:
#   * supervisord.conf: value carried through the env channel (%(ENV_x)s), never
#     spliced into the environment= grammar — inert to `"`, `,`, `|`, `&`, `\`.
#   * hermes.yaml: value escaped as literal data before the sed rewrite, with a
#     non-fatal guard so no content can abort boot.
# Same family as the closed #817 (content-dependent boot-brick).
#
# NOTE: the container's supervisord.conf is GENERATED by install-core.sh
# (_write_supervisord_conf), not COPYd from packages/integration/supervisord.conf
# (see Dockerfile). These tests therefore assert against the generated output, so
# a mechanism regression in the file that actually ships cannot pass silently.

ENTRYPOINT="$BATS_TEST_DIRNAME/../../packages/integration/entrypoint.sh"
PREFLIGHT="$BATS_TEST_DIRNAME/../../packages/install-core/preflight.sh"
INSTALL_CORE="$BATS_TEST_DIRNAME/../../packages/install-core/install-core.sh"

# Mirrors the entrypoint §5b two-plane escape into a double-quoted YAML scalar
# (BRAVE_API_KEY: "${BRAVE_API_KEY}"): YAML rules first (backslash, double-quote),
# then sed replacement rules (backslash, delimiter, back-reference). Portable sed
# (no -i) so it runs identically on GNU (container/CI) and BSD (macOS) sed.
# Writes the patched YAML to $2.
_patch_yaml() {
  local key="$1" out="$2"
  local repl="$key"
  repl="${repl//\\/\\\\}"   # YAML: backslash — must be first
  repl="${repl//\"/\\\"}"   # YAML: double-quote inside the scalar
  repl="${repl//\\/\\\\}"   # sed: backslash — must be first
  repl="${repl//|/\\|}"     # sed: delimiter
  repl="${repl//&/\\&}"     # sed: whole-match back-reference
  local tmpl="$BATS_TEST_TMPDIR/tmpl.yaml"
  printf 'mcp_servers:\n  brave:\n    env:\n      BRAVE_API_KEY: "${BRAVE_API_KEY}"\nsentinel: foxinthebox\n' > "$tmpl"
  sed "s|\${BRAVE_API_KEY}|${repl}|g" "$tmpl" > "$out"
}

# Parse the patched YAML with a real parser and echo the round-tripped key value.
_yaml_brave() {
  python3 -c 'import sys,yaml; print(yaml.safe_load(open(sys.argv[1]))["mcp_servers"]["brave"]["env"]["BRAVE_API_KEY"])' "$1"
}

_have_pyyaml() { python3 -c 'import yaml' >/dev/null 2>&1; }

# Run install-core.sh's real _write_supervisord_conf for one context, with the
# absolute /etc + /run paths sandboxed into $2 so no root is needed. Echoes the
# path to the generated conf. This exercises the actual branch + heredoc that
# ships, not a hand-copied expectation.
_generate_conf() {
  local ctx="$1" outroot="$2"
  local script="$BATS_TEST_TMPDIR/wsc_${ctx}.sh"
  {
    echo '_log() { :; }'
    sed -n '/^_write_supervisord_conf() {/,/^}/p' "$INSTALL_CORE" \
      | sed -e "s#/etc/supervisor#${outroot}/etc/supervisor#g" \
            -e "s#/etc/foxinthebox#${outroot}/etc/foxinthebox#g" \
            -e "s#/run/fitb#${outroot}/run/fitb#g" \
            -e "s#/run/foxinthebox#${outroot}/run/foxinthebox#g"
    echo '_write_supervisord_conf'
  } > "$script"
  FITB_CONTEXT="$ctx" FITB_APP_DIR="/app" FITB_DATA_DIR="/data" \
    EMBED_MODEL_FILENAME="" EMBED_MODEL_SHA256="" bash "$script" >/dev/null
  if [ "$ctx" = "docker" ]; then
    echo "${outroot}/etc/supervisor/supervisord.conf"
  else
    echo "${outroot}/etc/foxinthebox/supervisord.conf"
  fi
}

# ---------------------------------------------------------------------------
# Generated-output gates — the container conf that actually ships (#908).
# ---------------------------------------------------------------------------
@test "#908 container: generated gateway environment= carries NO BRAVE_API_KEY (inherited instead)" {
  # A `"` in the key would break supervisord's environment= grammar even via
  # %(ENV_x)s. The gateway inherits BRAVE_API_KEY from supervisord's process env
  # (entrypoint §6b export) instead, so it must not appear in environment=.
  local conf; conf="$(_generate_conf docker "$BATS_TEST_TMPDIR/docker")"
  run grep -F 'BRAVE_API_KEY' "$conf"
  [ "$status" -ne 0 ]
}

@test "#908 container: generated conf leaves no __BRAVE_API_KEY__ placeholder" {
  local conf; conf="$(_generate_conf docker "$BATS_TEST_TMPDIR/docker2")"
  run grep -F '__BRAVE_API_KEY__' "$conf"
  [ "$status" -ne 0 ]
}

@test "#908 container: entrypoint exports BRAVE_API_KEY for supervisord" {
  run grep -F 'export BRAVE_API_KEY="${BRAVE_API_KEY:-}"' "$ENTRYPOINT"
  [ "$status" -eq 0 ]
}

@test "#908 container: entrypoint no longer seds BRAVE into supervisord.conf" {
  run grep -nE 'sed .*__BRAVE_API_KEY__' "$ENTRYPOINT"
  [ "$status" -ne 0 ]
}

@test "#908 container: entrypoint escapes the key before the hermes.yaml rewrite" {
  run grep -F '_brave_repl="${_brave_repl//\\/\\\\}"' "$ENTRYPOINT"
  [ "$status" -eq 0 ]
}

@test "#908 container: entrypoint YAML-escapes a double-quote in the key" {
  run grep -F '_brave_repl="${_brave_repl//\"/\\\"}"' "$ENTRYPOINT"
  [ "$status" -eq 0 ]
}

# ---------------------------------------------------------------------------
# Source-text gates — desktop/.deb path. preflight runs as systemd
# ExecStartPre=, so the %(ENV_x)s recipe cannot be reused; the key must reach
# the gateway via run-with-env.sh sourcing hermes.env, with no supervisord.conf
# templating at all.
# ---------------------------------------------------------------------------
@test "#908 desktop: preflight no longer seds BRAVE into supervisord.conf" {
  run grep -nE 'sed .*__BRAVE_API_KEY__' "$PREFLIGHT"
  [ "$status" -ne 0 ]
}

@test "#908 desktop: preflight has no SUPERVISORD_CONF assignment (orphan removed)" {
  run grep -nE '^[[:space:]]*SUPERVISORD_CONF=' "$PREFLIGHT"
  [ "$status" -ne 0 ]
}

@test "#908 desktop: preflight escapes the key before the hermes.yaml rewrite" {
  run grep -F '_brave_repl="${_brave_repl//\\/\\\\}"' "$PREFLIGHT"
  [ "$status" -eq 0 ]
}

@test "#908 desktop: preflight YAML-escapes a double-quote in the key" {
  run grep -F '_brave_repl="${_brave_repl//\"/\\\"}"' "$PREFLIGHT"
  [ "$status" -eq 0 ]
}

@test "#908 desktop: generated gateway environment= carries no BRAVE_API_KEY" {
  # Desktop relies on run-with-env.sh sourcing hermes.env, never %(ENV_x)s
  # (ExecStartPre= != ExecStart=). The generated conf must carry no BRAVE entry.
  local conf; conf="$(_generate_conf bare-metal "$BATS_TEST_TMPDIR/deb")"
  run grep -F 'BRAVE_API_KEY' "$conf"
  [ "$status" -ne 0 ]
}

# ---------------------------------------------------------------------------
# Behavioral — the patched hermes.yaml is VALID YAML and the key round-trips
# to its exact value, for any metacharacter content. Parsed with a real YAML
# parser so a `"`/`\` that would corrupt the scalar is caught.
# ---------------------------------------------------------------------------
@test "#908 hermes.yaml: a quote+backslash key stays valid YAML and round-trips" {
  _have_pyyaml || skip "pyyaml not available (CI installs python3-yaml)"
  local out="$BATS_TEST_TMPDIR/hermes.yaml"
  # The RC acceptance trigger: sed metachars + supervisord-breakers + a quote.
  local key='a&b|c\d"e,f'
  _patch_yaml "$key" "$out"
  run _yaml_brave "$out"
  [ "$status" -eq 0 ]
  [ "$output" = "$key" ]
}

@test "#908 hermes.yaml: a key with sed metachars round-trips" {
  _have_pyyaml || skip "pyyaml not available (CI installs python3-yaml)"
  local out="$BATS_TEST_TMPDIR/hermes.yaml"
  local key='a|b&c\d'
  _patch_yaml "$key" "$out"
  run _yaml_brave "$out"
  [ "$status" -eq 0 ]
  [ "$output" = "$key" ]
}

@test "#908 hermes.yaml: an injection payload does not execute as a sed program" {
  _have_pyyaml || skip "pyyaml not available (CI installs python3-yaml)"
  local out="$BATS_TEST_TMPDIR/hermes.yaml"
  local key='abc|g;s|foxinthebox|INJECTED|g'
  _patch_yaml "$key" "$out"
  # Sentinel untouched: if the payload had run as a sed program it would have
  # rewritten this line to "sentinel: INJECTED".
  run grep -F 'sentinel: foxinthebox' "$out"
  [ "$status" -eq 0 ]
  run grep -F 'sentinel: INJECTED' "$out"
  [ "$status" -ne 0 ]
  # The whole payload round-trips as the key value (inert text, not executed).
  run _yaml_brave "$out"
  [ "$status" -eq 0 ]
  [ "$output" = "$key" ]
}

@test "#908 hermes.yaml: an ordinary alphanumeric key round-trips (no over-escaping)" {
  _have_pyyaml || skip "pyyaml not available (CI installs python3-yaml)"
  local out="$BATS_TEST_TMPDIR/hermes.yaml"
  local key='BSAplainKey123'
  _patch_yaml "$key" "$out"
  run _yaml_brave "$out"
  [ "$status" -eq 0 ]
  [ "$output" = "$key" ]
}
