#!/usr/bin/env bats
# tests/container/test_entrypoint_brave_key.bats
# Run: bats tests/container/test_entrypoint_brave_key.bats
#
# Regression gate for #908 — a BRAVE_API_KEY containing shell/sed/supervisord
# metacharacters must not brick boot. Two consuming surfaces, two mechanisms:
#   * supervisord.conf: value carried through the env channel (%(ENV_x)s), never
#     spliced into the environment= grammar — inert to `"`, `,`, `|`, `&`, `\`.
#   * hermes.yaml: value escaped as literal data before the sed rewrite, with a
#     non-fatal guard so no content can abort boot.
# Same family as the closed #817 (content-dependent boot-brick).
#
# NOTE: the container's supervisord.conf is GENERATED by install-core.sh
# (_write_supervisord_conf), not COPYd from packages/integration/supervisord.conf
# (see Dockerfile). These tests therefore assert against the generated output, so
# a mechanism regression in the file that actually ships cannot pass silently.

ENTRYPOINT="$BATS_TEST_DIRNAME/../../packages/integration/entrypoint.sh"
PREFLIGHT="$BATS_TEST_DIRNAME/../../packages/install-core/preflight.sh"
INSTALL_CORE="$BATS_TEST_DIRNAME/../../packages/install-core/install-core.sh"

# Mirrors the entrypoint §5b escape+rewrite. Portable sed (no -i) so the escape
# logic is exercised identically on GNU (container/CI) and BSD (macOS) sed.
_patch_yaml() {
  local key="$1" yaml="$2"
  local repl="$key"
  repl="${repl//\\/\\\\}"   # backslash — must be first
  repl="${repl//|/\\|}"     # sed delimiter
  repl="${repl//&/\\&}"     # whole-match back-reference
  sed "s|\${BRAVE_API_KEY}|${repl}|g" "$yaml"
}

# Run install-core.sh's real _write_supervisord_conf for one context, with the
# absolute /etc + /run paths sandboxed into $2 so no root is needed. Echoes the
# path to the generated conf. This exercises the actual branch + heredoc that
# ships, not a hand-copied expectation.
_generate_conf() {
  local ctx="$1" outroot="$2"
  local script="$BATS_TEST_TMPDIR/wsc_${ctx}.sh"
  {
    echo '_log() { :; }'
    sed -n '/^_write_supervisord_conf() {/,/^}/p' "$INSTALL_CORE" \
      | sed -e "s#/etc/supervisor#${outroot}/etc/supervisor#g" \
            -e "s#/etc/foxinthebox#${outroot}/etc/foxinthebox#g" \
            -e "s#/run/fitb#${outroot}/run/fitb#g" \
            -e "s#/run/foxinthebox#${outroot}/run/foxinthebox#g"
    echo '_write_supervisord_conf'
  } > "$script"
  FITB_CONTEXT="$ctx" FITB_APP_DIR="/app" FITB_DATA_DIR="/data" \
    EMBED_MODEL_FILENAME="" EMBED_MODEL_SHA256="" bash "$script" >/dev/null
  if [ "$ctx" = "docker" ]; then
    echo "${outroot}/etc/supervisor/supervisord.conf"
  else
    echo "${outroot}/etc/foxinthebox/supervisord.conf"
  fi
}

# ---------------------------------------------------------------------------
# Generated-output gates — the container conf that actually ships (#908).
# ---------------------------------------------------------------------------
@test "#908 container: generated gateway environment= carries %(ENV_BRAVE_API_KEY)s" {
  local conf; conf="$(_generate_conf docker "$BATS_TEST_TMPDIR/docker")"
  run grep -F 'BRAVE_API_KEY="%(ENV_BRAVE_API_KEY)s"' "$conf"
  [ "$status" -eq 0 ]
}

@test "#908 container: generated conf leaves no __BRAVE_API_KEY__ placeholder" {
  local conf; conf="$(_generate_conf docker "$BATS_TEST_TMPDIR/docker2")"
  run grep -F '__BRAVE_API_KEY__' "$conf"
  [ "$status" -ne 0 ]
}

@test "#908 container: entrypoint exports BRAVE_API_KEY for supervisord" {
  run grep -F 'export BRAVE_API_KEY="${BRAVE_API_KEY:-}"' "$ENTRYPOINT"
  [ "$status" -eq 0 ]
}

@test "#908 container: entrypoint no longer seds BRAVE into supervisord.conf" {
  run grep -nE 'sed .*__BRAVE_API_KEY__' "$ENTRYPOINT"
  [ "$status" -ne 0 ]
}

@test "#908 container: entrypoint escapes the key before the hermes.yaml rewrite" {
  run grep -F '_brave_repl="${_brave_repl//\\/\\\\}"' "$ENTRYPOINT"
  [ "$status" -eq 0 ]
}

# ---------------------------------------------------------------------------
# Source-text gates — desktop/.deb path. preflight runs as systemd
# ExecStartPre=, so the %(ENV_x)s recipe cannot be reused; the key must reach
# the gateway via run-with-env.sh sourcing hermes.env, with no supervisord.conf
# templating at all.
# ---------------------------------------------------------------------------
@test "#908 desktop: preflight no longer seds BRAVE into supervisord.conf" {
  run grep -nE 'sed .*__BRAVE_API_KEY__' "$PREFLIGHT"
  [ "$status" -ne 0 ]
}

@test "#908 desktop: preflight has no SUPERVISORD_CONF assignment (orphan removed)" {
  run grep -nE '^[[:space:]]*SUPERVISORD_CONF=' "$PREFLIGHT"
  [ "$status" -ne 0 ]
}

@test "#908 desktop: preflight escapes the key before the hermes.yaml rewrite" {
  run grep -F '_brave_repl="${_brave_repl//\\/\\\\}"' "$PREFLIGHT"
  [ "$status" -eq 0 ]
}

@test "#908 desktop: generated gateway environment= carries no BRAVE_API_KEY" {
  # Desktop relies on run-with-env.sh sourcing hermes.env, never %(ENV_x)s
  # (ExecStartPre= != ExecStart=). The generated conf must carry no BRAVE entry.
  local conf; conf="$(_generate_conf bare-metal "$BATS_TEST_TMPDIR/deb")"
  run grep -F 'BRAVE_API_KEY' "$conf"
  [ "$status" -ne 0 ]
}

# ---------------------------------------------------------------------------
# Behavioral — the escape technique lands the value verbatim, no injection.
# ---------------------------------------------------------------------------
@test "#908 hermes.yaml: a key with sed metachars lands verbatim" {
  local yaml="$BATS_TEST_TMPDIR/hermes.yaml"
  printf 'brave:\n  api_key: ${BRAVE_API_KEY}\n' > "$yaml"
  run _patch_yaml 'a|b&c\d' "$yaml"
  [ "$status" -eq 0 ]
  [[ "$output" == *'api_key: a|b&c\d'* ]]
}

@test "#908 hermes.yaml: an injection payload does not execute as a sed program" {
  local yaml="$BATS_TEST_TMPDIR/hermes.yaml"
  printf 'brave:\n  api_key: ${BRAVE_API_KEY}\nsentinel: foxinthebox\n' > "$yaml"
  run _patch_yaml 'abc|g;s|foxinthebox|INJECTED|g' "$yaml"
  [ "$status" -eq 0 ]
  # The sentinel must survive untouched: if the payload had run as a sed program
  # it would have rewritten this line to "sentinel: INJECTED".
  [[ "$output" == *"sentinel: foxinthebox"* ]]
  [[ "$output" != *"sentinel: INJECTED"* ]]
  # The whole payload lands literally as the key value (INJECTED here is inert
  # text inside the key, not an executed substitution).
  [[ "$output" == *'api_key: abc|g;s|foxinthebox|INJECTED|g'* ]]
}

@test "#908 hermes.yaml: an ordinary alphanumeric key lands verbatim (no over-escaping)" {
  local yaml="$BATS_TEST_TMPDIR/hermes.yaml"
  printf 'brave:\n  api_key: ${BRAVE_API_KEY}\n' > "$yaml"
  run _patch_yaml 'BSAplainKey123' "$yaml"
  [ "$status" -eq 0 ]
  [[ "$output" == *'api_key: BSAplainKey123'* ]]
}
